In [39]:
import tensorflow as tf;
import numpy as np;
import matplotlib.pyplot as plt;
print(tf.__version__);
import pandas as pd;

from sklearn.preprocessing import StandardScaler;
from sklearn.preprocessing import MinMaxScaler;
from sklearn.metrics import mean_squared_error;

2.6.0


In [33]:
pd.set_option('display.max_columns', 300);
pd.set_option('display.max_rows', 300);
tf.keras.backend.set_floatx('float64');

In [36]:
a = np.array([[1,2,3],[4,5,6],[7,8,10]]);

In [44]:
sc = MinMaxScaler();
b = sc.fit_transform(a)

In [57]:
print(sc.data_min_[0], sc.data_range_[0])


1.0 6.0


In [26]:
a[:,2] = np.random.permutation(a[:,2])
print(a)

[[1 2 6]
 [4 5 9]
 [7 8 3]]


In [30]:
temp = pd.read_csv("../data/full_dataset_unscaled.csv", index_col=0)

In [35]:
temp.shape

(78060, 97)